const cfg=window.INCENTIFY_EMS_CONFIG,api=window.incentifyEmsApi,$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={token:sessionStorage.getItem(cfg.SESSION_KEY)||'',user:null,settings:{},dashboard:{},employees:[],attendance:[],holidays:[],exceptions:[],accessUsers:[],selectedEmployee:null,selectedPunchIds:new Set(),selectedAccessEmail:'',calendarMonth:new Date(new Date().getFullYear(),new Date().getMonth(),1),workday:null,mailDiagnostics:null,mailLog:[],systemRuns:[]};
const pageMeta={dashboard:['WORKFORCE OVERVIEW','Dashboard'],employees:['EMPLOYEE MANAGEMENT','Employees'],attendance:['ATTENDANCE MANAGEMENT','Attendance'],schedule:['CALENDAR & EXCEPTIONS','Schedule'],reports:['REPORTING & BACKUP','Reports'],access:['ACCESS CONTROL','Portal Access'],settings:['SYSTEM CONTROL','Settings']};
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=v=>{if(!v)return'—';const d=new Date(v);return isNaN(d)?String(v):d.toLocaleString();};
const fmtTime=v=>{if(!v)return'—';const d=new Date(v);return isNaN(d)?String(v):d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});};
const todayKey=()=>{const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const userAgent=()=>navigator.userAgent.slice(0,480);
const call=(action,payload={},timeout)=>api.call(action,{token:state.token,...payload},timeout);
function toast(m,t='info',ms=4200){const e=document.createElement('div');e.className='toast '+t;e.textContent=m;$('#toastStack').appendChild(e);setTimeout(()=>e.remove(),ms)}
function setInlineMessage(id,message,type='neutral'){const e=$('#'+id);if(!e)return;e.hidden=!message;e.textContent=message||'';e.className='inline-message '+type}
function openModal(id){const m=$('#'+id);if(!m)return;m.hidden=false;document.body.classList.add('modal-open');requestAnimationFrame(()=>{const f=m.querySelector('input:not([type=hidden]),select,textarea,button');if(f)f.focus()})}
function closeModal(id,force=false){const m=$('#'+id);if(!m||m.hidden)return;if(!force&&m.dataset.busy==='1')return;m.hidden=true;m.dataset.busy='0';if(!$$('.app-modal').some(x=>!x.hidden))document.body.classList.remove('modal-open')}
function setModalBusy(id,on){const m=$('#'+id);if(!m)return;m.dataset.busy=on?'1':'0';$$('button,input,select,textarea',m).forEach(x=>{if(x.id==='saveEmployeeBtn'||x.id==='createAccessUserBtn')return;if(x.dataset.keepEnabled!=='1')x.disabled=Boolean(on)})}
let pendingConfirmation=null;
let pendingConfirmationText='';
function confirmAction(title,message,confirmLabel='Confirm',requiredText=''){
  return new Promise(resolve=>{
    pendingConfirmation=resolve;pendingConfirmationText=String(requiredText||'');
    $('#confirmDialogTitle').textContent=title;$('#confirmDialogMessage').textContent=message;$('#confirmDialogAccept').textContent=confirmLabel;
    const wrap=$('#confirmPhraseWrap'),input=$('#confirmPhraseInput'),label=$('#confirmPhraseLabel');
    input.value='';wrap.hidden=!pendingConfirmationText;label.textContent=pendingConfirmationText?`Type ${pendingConfirmationText} to continue`:'';
    $('#confirmDialogAccept').disabled=Boolean(pendingConfirmationText);setInlineMessage('confirmDialogInlineMessage','');
    openModal('confirmDialog');
  })
}
function settleConfirmation(value){
  if(value&&pendingConfirmationText&&$('#confirmPhraseInput').value.trim()!==pendingConfirmationText){setInlineMessage('confirmDialogInlineMessage',`Type ${pendingConfirmationText} exactly to continue.`,'error');return}
  const done=pendingConfirmation;pendingConfirmation=null;pendingConfirmationText='';closeModal('confirmDialog',true);if(done)done(Boolean(value));
}
function busy(b,on,label){if(!b)return;if(on){b.dataset.old=b.textContent;b.disabled=true;b.textContent=label||'Working…'}else{b.disabled=false;b.textContent=b.dataset.old||b.textContent}}
function clearSession(){state.token='';sessionStorage.removeItem(cfg.SESSION_KEY);sessionStorage.removeItem(cfg.USER_KEY)}
async function init(){
  bind();const t=todayKey();$('#attendanceStart').value=t;$('#attendanceEnd').value=t;$('#concessionDate').value=t;
  if(!state.token){location.replace('./index.html');return}
  try{
    const r=await call('bootstrapAdmin');if(r.user&&r.user.portal==='employee'){location.replace('./employee.html');return}
    $('#backendState').textContent='Online';if(r.serverMs!=null)$('#backendState').title=`Backend processing: ${r.serverMs} ms`;
    state.user=r.user;state.settings=r.settings||{};state.dashboard=r.dashboard||{};state.employees=r.employees||[];state.accessUsers=[];state.holidays=r.holidays||[];state.exceptions=r.exceptions||[];state.workday=r.workday||null;
    renderAll();applyPermissions();navigate('dashboard');
  }catch(e){clearSession();sessionStorage.setItem('incentify_ems_login_flash',e.message||'Your session expired. Please sign in again.');location.replace('./index.html')}
}
function bind(){
  $('#logoutBtn').onclick=logout;$('#menuBtn').onclick=()=>$('.sidebar').classList.toggle('open');$$('.nav-item').forEach(b=>b.onclick=()=>navigate(b.dataset.page));$$('[data-page-jump]').forEach(b=>b.onclick=()=>navigate(b.dataset.pageJump));
  $('#addEmployeeBtn').onclick=()=>openEmployee(null);$('#editEmployeeBtn').onclick=()=>state.selectedEmployee&&openEmployee(state.selectedEmployee);$('#employeeForm').onsubmit=e=>{e.preventDefault();saveEmployee()};$('#employeeSearch').oninput=renderEmployees;$('#deleteEmployeeBtn').onclick=deleteEmployee;$('#sendEnrollmentBtn').onclick=sendEnrollment;$('#resendAttendanceBtn').onclick=resendAttendance;
  $('#employeeDialogClose').onclick=()=>closeModal('employeeDialog');$('#cancelEmployeeBtn').onclick=()=>closeModal('employeeDialog');
  $('#applyAttendanceFilters').onclick=loadAttendance;$('#selectAllAttendance').onchange=toggleAll;$('#deleteSelectedAttendance').onclick=deleteAttendance;
  $('#calendarPrev').onclick=()=>{state.calendarMonth=new Date(state.calendarMonth.getFullYear(),state.calendarMonth.getMonth()-1,1);renderCalendar()};$('#calendarNext').onclick=()=>{state.calendarMonth=new Date(state.calendarMonth.getFullYear(),state.calendarMonth.getMonth()+1,1);renderCalendar()};$('#saveHolidayBtn').onclick=saveHoliday;$('#issueConcessionBtn').onclick=issueConcession;
  $('#exportXlsxBtn').onclick=exportXlsx;$('#cloudBackupBtn').onclick=cloudBackup;$('#addAccessBtn').onclick=openAccessDialog;$('#accessForm').onsubmit=e=>{e.preventDefault();createAccessUser()};$('#accessDialogClose').onclick=()=>closeModal('accessDialog');$('#cancelAccessBtn').onclick=()=>closeModal('accessDialog');$('#toggleAccessBtn').onclick=toggleAccess;$('#deleteAccessBtn').onclick=deleteAccess;$('#saveSettingsBtn').onclick=saveSettings;
  $('#refreshMailHealthBtn').onclick=loadMailDiagnostics;$('#sendTestMailBtn').onclick=sendTestMail;$('#refreshMailLogBtn').onclick=loadMailLog;$('#refreshSystemRunsBtn').onclick=loadSystemRuns;$('#confirmDialogClose').onclick=()=>settleConfirmation(false);$('#confirmDialogCancel').onclick=()=>settleConfirmation(false);$('#confirmDialogAccept').onclick=()=>settleConfirmation(true);$('#confirmPhraseInput').oninput=()=>{$('#confirmDialogAccept').disabled=Boolean(pendingConfirmationText)&&$('#confirmPhraseInput').value.trim()!==pendingConfirmationText};
  $$('[data-close-modal]').forEach(x=>x.onclick=()=>x.dataset.closeModal==='confirmDialog'?settleConfirmation(false):closeModal(x.dataset.closeModal));
  document.addEventListener('keydown',e=>{if(e.key!=='Escape')return;const open=$$('.app-modal').find(x=>!x.hidden);if(!open)return;if(open.id==='confirmDialog')settleConfirmation(false);else closeModal(open.id)});
}
function applyPermissions(){
  const admin=String(state.user?.role||'').toUpperCase()==='ADMIN';
  const accessNav=$('.nav-item[data-page="access"]'),settingsNav=$('.nav-item[data-page="settings"]');
  if(accessNav)accessNav.hidden=!admin;if(settingsNav)settingsNav.hidden=!admin;
}
async function logout(){try{await api.call('logout',{token:state.token,userAgent:userAgent()})}catch(_){}clearSession();location.replace('./index.html')}
function navigate(p){
  if(!pageMeta[p])return;const admin=String(state.user?.role||'').toUpperCase()==='ADMIN';if((p==='access'||p==='settings')&&!admin){toast('Administrator permission is required.','error');p='dashboard'}
  $$('.page').forEach(x=>x.classList.toggle('active-page',x.id===`page-${p}`));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===p));$('#pageEyebrow').textContent=pageMeta[p][0];$('#pageTitle').textContent=pageMeta[p][1];$('.sidebar').classList.remove('open');
  if(p==='attendance')void loadAttendance();if(p==='access'){void loadAccess();void loadMailDiagnostics();void loadMailLog()}if(p==='schedule')void refreshSchedule();if(p==='settings')void loadSystemRuns();
}
function renderAll(){renderUser();renderDashboard();renderEmployees();renderSettings();renderAccess();renderCalendar();renderHolidayTable();renderExceptions();populateEmployees()}
function renderUser(){const u=state.user||{};$('#userName').textContent=u.name||u.email||'Admin';$('#userRole').textContent=u.role||'—';$('#userInitial').textContent=(u.name||u.email||'I')[0].toUpperCase()}
function renderDashboard(){const d=state.dashboard||{},s=state.settings||{};$('#metricTotal').textContent=d.totalEmployees||0;$('#metricPresent').textContent=d.presentToday||0;$('#metricAbsent').textContent=d.absentToday||0;$('#metricIn').textContent=d.currentlyIn||0;$('#metricPunches').textContent=d.punchesToday||0;$('#navEmployeeCount').textContent=d.totalEmployees||0;$('#navAttendanceCount').textContent=d.punchesToday||0;$('#dashLinkWindow').textContent=`${s.attendance_link_open_time||'10:00'}–${s.attendance_link_close_time||'10:30'} IST`;$('#dashShiftHours').textContent=`${(Number(s.shift_duration_minutes||480)/60).toFixed(Number(s.shift_duration_minutes||480)%60?1:0)} hours`;$('#dashOfficeRadius').textContent=`${s.office_radius_meters||150} m`;const next=state.holidays.filter(h=>h.date>=todayKey()).sort((a,b)=>a.date.localeCompare(b.date))[0];$('#dashNextHoliday').textContent=next?`${next.date} • ${next.name}`:'No custom holiday scheduled';const w=state.workday||{};$('#todayWorkdayBadge').textContent=w.isWorkday?'WORKDAY':(w.isSunday?'SUNDAY':'HOLIDAY');$('#todayWorkdayBadge').className='badge '+(w.isWorkday?'badge-success':'badge-warn');$('#todayWorkdayMessage').textContent=w.isWorkday?'10 AM attendance links are enabled today.':(w.isSunday?'Sunday is automatically closed. No attendance email is sent.':`Closed: ${w.holiday?.name||'Holiday'}. No attendance email is sent.`);const rows=d.recent||[];$('#recentActivity').classList.toggle('empty-state',!rows.length);$('#recentActivity').innerHTML=rows.length?rows.map(p=>`<div class="activity-item"><span class="punch-dot ${p.punchType==='IN'?'punch-in':'punch-out'}">${esc(p.punchType)}</span><div><b>${esc(p.fullName)}</b><small>${esc(p.employeeCode)} • ${esc(p.source||'')}</small></div><small>${esc(fmtTime(p.punchTime))}</small></div>`).join(''):'No attendance records yet.';updateMode()}
function renderEmployees(){const q=$('#employeeSearch').value.trim().toLowerCase(),rows=!q?state.employees:state.employees.filter(e=>[e.employeeCode,e.fullName,e.email,e.department,e.designation].join(' ').toLowerCase().includes(q));$('#employeeTableBody').innerHTML=rows.map(e=>{const selected=state.selectedEmployee?.employeeCode===e.employeeCode,face=e.faceRecognitionEnabled?`<span class="badge badge-success">Enrolled · ${Number(e.biometricSampleCount||0)} samples</span>`:'<span class="badge badge-warn">Not enrolled</span>';return `<tr data-code="${esc(e.employeeCode)}" class="${selected?'selected':''}"><td class="center"><input class="employee-select-check" type="checkbox" data-code="${esc(e.employeeCode)}" ${selected?'checked':''} aria-label="Select ${esc(e.fullName)}"></td><td><b>${esc(e.employeeCode)}</b></td><td>${esc(e.fullName)}</td><td>${esc(e.email||'—')}</td><td>${esc(e.department||'—')}</td><td>${esc(e.designation||'—')}</td><td>${face}</td><td><span class="badge ${e.status==='Active'?'badge-success':'badge-neutral'}">${esc(e.status)}</span></td></tr>`}).join('');$$('#employeeTableBody tr[data-code]').forEach(tr=>tr.onclick=e=>{if(e.target.matches('input[type=checkbox]'))return;selectEmployee(tr.dataset.code)});$$('.employee-select-check').forEach(c=>c.onchange=()=>{if(c.checked)selectEmployee(c.dataset.code);else if(state.selectedEmployee?.employeeCode===c.dataset.code)clearEmployeeSelection()})}
function selectEmployee(code){state.selectedEmployee=state.employees.find(e=>e.employeeCode===code)||null;renderEmployees();const e=state.selectedEmployee;if(!e){clearEmployeeSelection();return}$('#selectedEmployeeBar').innerHTML=`<b>${esc(e.fullName)} • ${esc(e.employeeCode)}</b><span>${esc(e.email||'No email')} • ${esc(e.department||'—')} • Face: ${e.faceRecognitionEnabled?`enrolled (${Number(e.biometricSampleCount||0)} verified samples`:'not enrolled'}</span>`;['editEmployeeBtn','deleteEmployeeBtn','sendEnrollmentBtn','resendAttendanceBtn'].forEach(id=>$('#'+id).disabled=false)}
function clearEmployeeSelection(){state.selectedEmployee=null;$('#selectedEmployeeBar').innerHTML='<b>No employee selected</b><span>Select an employee to manage access or attendance links.</span>';['editEmployeeBtn','deleteEmployeeBtn','sendEnrollmentBtn','resendAttendanceBtn'].forEach(id=>$('#'+id).disabled=true);renderEmployees()}
function openEmployee(e){
  $('#employeeDialogTitle').textContent=e?'Edit employee':'Add employee';$('#employeeCode').value=e?.employeeCode||'';$('#employeeFullName').value=e?.fullName||'';$('#employeeEmail').value=e?.email||'';$('#employeeMobile').value=e?.mobile||'';$('#employeeDepartment').value=e?.department||'';$('#employeeDesignation').value=e?.designation||'';$('#employeeBranch').value=e?.branch||'';$('#employeeJoiningDate').value=e?.joiningDate||'';$('#employeeShift').value=e?.shiftName||'General';$('#employeeStatus').value=e?.status||'Active';$('#employeeEmergency').value=e?.emergencyContact||'';$('#employeeAddress').value=e?.address||'';$('#employeeNotes').value=e?.notes||'';setInlineMessage('employeeFormMessage','');openModal('employeeDialog')
}
function employeePayload(){return{employeeCode:$('#employeeCode').value,fullName:$('#employeeFullName').value.trim(),email:$('#employeeEmail').value.trim(),mobile:$('#employeeMobile').value.trim(),department:$('#employeeDepartment').value.trim(),designation:$('#employeeDesignation').value.trim(),branch:$('#employeeBranch').value.trim(),joiningDate:$('#employeeJoiningDate').value,shiftName:$('#employeeShift').value.trim(),status:$('#employeeStatus').value,emergencyContact:$('#employeeEmergency').value.trim(),address:$('#employeeAddress').value.trim(),notes:$('#employeeNotes').value.trim()}}
async function saveEmployee(){
  const form=$('#employeeForm'),d=employeePayload(),btn=$('#saveEmployeeBtn');if(!form.checkValidity()){form.reportValidity();return}setInlineMessage('employeeFormMessage','');busy(btn,true,'Saving…');setModalBusy('employeeDialog',true);
  try{
    const a=d.employeeCode?'updateEmployee':'createEmployee',r=await call(a,{employee:d}),saved=r.employee;
    const i=state.employees.findIndex(x=>x.employeeCode===saved.employeeCode);if(i>=0)state.employees[i]=saved;else state.employees.push(saved);state.employees.sort((a,b)=>a.employeeCode.localeCompare(b.employeeCode));
    state.selectedEmployee=saved;renderEmployees();populateEmployees();closeModal('employeeDialog',true);toast(d.employeeCode?'Employee updated.':'Employee added.','success');void reloadDashboard();
  }catch(e){setInlineMessage('employeeFormMessage',e.message,'error')}finally{setModalBusy('employeeDialog',false);busy(btn,false)}
}
async function deleteEmployee(){const e=state.selectedEmployee;if(!e)return;const ok=await confirmAction('Archive employee',`Archive ${e.fullName}? Attendance history will be retained and portal access disabled.`,'Archive employee');if(!ok)return;const b=$('#deleteEmployeeBtn');busy(b,true,'Archiving…');try{await call('deleteEmployee',{employeeCode:e.employeeCode});state.employees=state.employees.filter(x=>x.employeeCode!==e.employeeCode);clearEmployeeSelection();populateEmployees();toast('Employee archived.','success');void reloadDashboard()}catch(x){toast(x.message,'error')}finally{busy(b,false)}}
async function sendEnrollment(){const e=state.selectedEmployee;if(!e)return;const b=$('#sendEnrollmentBtn');busy(b,true,'Sending…');try{await call('sendEnrollmentLink',{employeeCode:e.employeeCode});toast('Secure enrollment link emailed.','success')}catch(x){toast(x.message,'error')}finally{busy(b,false)}}
async function resendAttendance(){const e=state.selectedEmployee;if(!e)return;const b=$('#resendAttendanceBtn');busy(b,true,'Sending…');try{const r=await call('resendTodayAttendanceLink',{employeeCode:e.employeeCode});toast(`Attendance link sent. Expires ${fmtTime(r.validUntil)}.`,'success')}catch(x){toast(x.message,'error')}finally{busy(b,false)}}
function populateEmployees(){const opts=state.employees.filter(e=>e.status==='Active').map(e=>`<option value="${esc(e.employeeCode)}">${esc(e.employeeCode)} • ${esc(e.fullName)}</option>`).join('');$('#attendanceEmployee').innerHTML='<option value="">All employees</option>'+opts;$('#concessionEmployee').innerHTML='<option value="">Select employee</option>'+opts}
function filters(){return{startDate:$('#attendanceStart').value,endDate:$('#attendanceEnd').value,employeeCode:$('#attendanceEmployee').value}}
async function loadAttendance(){try{const r=await call('listAttendance',{filters:filters()});state.attendance=r.attendance||[];state.selectedPunchIds.clear();renderAttendance()}catch(e){toast(e.message,'error')}}
function renderAttendance(){$('#attendanceTableBody').innerHTML=state.attendance.map(p=>`<tr><td class="center"><input class="attendance-check" type="checkbox" data-id="${esc(p.id)}"></td><td><b>${esc(p.fullName)}</b><br><small>${esc(p.employeeCode)}</small></td><td><span class="badge ${p.punchType==='IN'?'badge-success':'badge-neutral'}">${esc(p.punchType)}</span></td><td>${esc(fmt(p.punchTime))}</td><td>${esc(p.requiredOutAt?fmt(p.requiredOutAt):'—')}</td><td>${esc(p.source||p.method||'—')}</td><td>${p.distanceMeters==null?'—':esc(p.distanceMeters+' m')}</td></tr>`).join('');$$('.attendance-check').forEach(c=>c.onchange=()=>{c.checked?state.selectedPunchIds.add(c.dataset.id):state.selectedPunchIds.delete(c.dataset.id);selection()});$('#selectAllAttendance').checked=false;selection()}
function toggleAll(e){state.selectedPunchIds.clear();$$('.attendance-check').forEach(c=>{c.checked=e.target.checked;if(c.checked)state.selectedPunchIds.add(c.dataset.id)});selection()}
function selection(){const n=state.selectedPunchIds.size;$('#attendanceSelectionCount').textContent=`${n} selected`;$('#deleteSelectedAttendance').disabled=!n||String(state.settings.data_mode||'production')!=='testing'}
async function deleteAttendance(){const ok=await confirmAction('Delete test attendance',`Delete ${state.selectedPunchIds.size} selected TEST attendance record(s)? This is blocked in Production mode.`,'Delete records','DELETE');if(!ok)return;try{await call('deleteAttendance',{punchIds:[...state.selectedPunchIds],reason:'V20 testing cleanup'});state.selectedPunchIds.clear();await loadAttendance();await reloadDashboard();toast('Attendance deleted.','success')}catch(e){toast(e.message,'error')}}
function renderCalendar(){const d=state.calendarMonth,y=d.getFullYear(),m=d.getMonth();$('#calendarTitle').textContent=d.toLocaleString([],{month:'long',year:'numeric'});const first=new Date(y,m,1),days=new Date(y,m+1,0).getDate(),offset=first.getDay(),today=todayKey();let html=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=>`<div class="calendar-weekday">${x}</div>`).join('');for(let i=0;i<offset;i++)html+='<div class="calendar-day empty"></div>';for(let day=1;day<=days;day++){const key=`${y}-${String(m+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`,date=new Date(y,m,day),sun=date.getDay()===0,h=state.holidays.find(x=>x.date===key);html+=`<div class="calendar-day ${sun?'sunday':''} ${h?'custom-holiday':''} ${key===today?'today':''}"><b>${day}</b>${sun?'<small>Sunday</small>':''}${h?`<small>${esc(h.name)}</small>`:''}</div>`}$('#holidayCalendar').innerHTML=html}
function renderHolidayTable(){$('#holidayTableBody').innerHTML=state.holidays.map(h=>`<tr><td>${esc(h.date)}</td><td><b>${esc(h.name)}</b><br><small>${esc(h.notes||'')}</small></td><td>${esc(h.type)}</td><td><button class="btn btn-ghost holiday-delete" data-id="${esc(h.holidayId)}">Remove</button></td></tr>`).join('');$$('.holiday-delete').forEach(b=>b.onclick=()=>removeHoliday(b.dataset.id))}
async function saveHoliday(){const b=$('#saveHolidayBtn'),holiday={date:$('#holidayDate').value,name:$('#holidayName').value.trim(),type:$('#holidayType').value,notes:$('#holidayNotes').value.trim()};busy(b,true,'Saving…');try{await call('saveHoliday',{holiday});$('#holidayName').value='';$('#holidayNotes').value='';await refreshSchedule();toast('Holiday added.','success')}catch(e){toast(e.message,'error')}finally{busy(b,false)}}
async function removeHoliday(id){const ok=await confirmAction('Remove holiday','Remove this holiday from the company calendar?','Remove holiday');if(!ok)return;try{await call('deleteHoliday',{holidayId:id});await refreshSchedule();toast('Holiday removed.','success')}catch(e){toast(e.message,'error')}}
function renderExceptions(){const by=Object.fromEntries(state.employees.map(e=>[e.employeeCode,e.fullName]));$('#exceptionTableBody').innerHTML=state.exceptions.map(x=>`<tr><td>${esc(by[x.employeeCode]||x.employeeCode)}</td><td>${esc(x.date)}</td><td>${esc(fmtTime(x.validUntil))}</td><td>${esc(x.reason)}</td><td><span class="badge ${x.status==='USED'?'badge-success':'badge-neutral'}">${esc(x.status)}</span></td></tr>`).join('')}
async function issueConcession(){const exception={employeeCode:$('#concessionEmployee').value,date:$('#concessionDate').value,validUntilTime:$('#concessionUntil').value,reason:$('#concessionReason').value.trim()},b=$('#issueConcessionBtn');busy(b,true,'Sending…');try{const r=await call('createLateConcession',{exception});$('#concessionReason').value='';await refreshSchedule();toast(`Late link emailed. Valid until ${fmtTime(r.validUntil)}.`,'success')}catch(e){toast(e.message,'error')}finally{busy(b,false)}}
async function refreshSchedule(){try{const [h,x]=await Promise.all([call('listHolidays'),call('listAttendanceExceptions')]);state.holidays=h.holidays||[];state.exceptions=x.exceptions||[];renderCalendar();renderHolidayTable();renderExceptions();renderDashboard()}catch(e){toast(e.message,'error')}}
function b64Bytes(value){const bin=atob(String(value||'')),out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return out}
async function sha256Hex(bytes){if(!globalThis.crypto?.subtle)return'';const digest=await crypto.subtle.digest('SHA-256',bytes);return[...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function downloadSecureTicket(meta,statusEl){if(!meta?.token)throw new Error('The backend did not return a secure download ticket.');const chunks=[];let offset=0,total=Number(meta.totalBytes||0),received=0,filename=meta.filename||'INCENTIFY_download',mime=meta.mimeType||'application/octet-stream';while(offset<total||offset===0){const r=await call('downloadExportChunk',{downloadToken:meta.token,offset},45000),bytes=b64Bytes(r.base64);chunks.push(bytes);received+=bytes.length;offset=Number(r.nextOffset||received);filename=r.filename||filename;mime=r.mimeType||mime;if(statusEl)statusEl.textContent=`Downloading ${Math.min(100,Math.round(received/Math.max(1,total)*100))}% • ${filename}`;if(r.done)break}const all=new Uint8Array(received);let pos=0;chunks.forEach(c=>{all.set(c,pos);pos+=c.length});if(meta.sha256&&globalThis.crypto?.subtle){const actual=await sha256Hex(all);if(actual&&actual.toLowerCase()!==String(meta.sha256).toLowerCase())throw new Error('Secure download integrity check failed. Generate the file again.')}const url=URL.createObjectURL(new Blob([all],{type:mime})),a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),5000);return{filename,bytes:received}}
async function exportXlsx(){const b=$('#exportXlsxBtn'),statusEl=$('#exportStatus');busy(b,true,'Generating…');try{const r=await call('exportAttendanceXlsx',{filters:filters()},90000);statusEl.textContent=`Preparing secure download • ${r.count} records`;const d=await downloadSecureTicket(r.download,statusEl);statusEl.textContent=`Downloaded ${r.count} records • ${d.filename}`;toast('Attendance workbook downloaded securely.','success')}catch(e){statusEl.textContent=e.message;toast(e.message,'error')}finally{busy(b,false)}}
async function cloudBackup(){const b=$('#cloudBackupBtn'),statusEl=$('#backupStatus');busy(b,true,'Creating…');try{const r=await call('createCloudBackup',{},90000);statusEl.textContent='Preparing secure backup download…';const d=await downloadSecureTicket(r.download,statusEl);statusEl.textContent=`Downloaded • ${d.filename}`;toast('Backup ZIP downloaded securely.','success')}catch(e){statusEl.textContent=e.message;toast(e.message,'error')}finally{busy(b,false)}}
async function loadAccess(){try{const r=await call('listAccessUsers');state.accessUsers=r.users||[];if(!state.accessUsers.some(x=>x.email===state.selectedAccessEmail))state.selectedAccessEmail='';renderAccess();if(r.serverMs!=null)$('#backendState').title=`Last backend processing: ${r.serverMs} ms`}catch(e){toast(e.message,'error')}}
function openAccessDialog(){$('#accessNewName').value='';$('#accessNewEmail').value='';$('#accessNewRole').value='ADMIN';setInlineMessage('accessFormMessage','');openModal('accessDialog')}
async function createAccessUser(){
  const form=$('#accessForm'),b=$('#createAccessUserBtn'),account={name:$('#accessNewName').value.trim(),email:$('#accessNewEmail').value.trim(),role:$('#accessNewRole').value};if(!form.checkValidity()){form.reportValidity();return}setInlineMessage('accessFormMessage','');busy(b,true,'Adding…');setModalBusy('accessDialog',true);
  try{const r=await call('createAccessUser',{account});state.accessUsers.push(r.user);state.accessUsers.sort((a,b)=>a.email.localeCompare(b.email));state.selectedAccessEmail=r.user.email;renderAccess();closeModal('accessDialog',true);toast(`Authorized ${r.user.role} account added: ${r.user.email}`,'success')}
  catch(e){setInlineMessage('accessFormMessage',e.message,'error')}finally{setModalBusy('accessDialog',false);busy(b,false)}
}
function renderAccess(){
  const body=$('#accessTableBody');body.innerHTML=state.accessUsers.length?state.accessUsers.map(u=>{const selected=state.selectedAccessEmail===u.email;return `<tr data-email="${esc(u.email)}" class="${selected?'selected':''}"><td class="center"><input class="access-select-check" type="checkbox" data-email="${esc(u.email)}" ${selected?'checked':''} aria-label="Select ${esc(u.email)}"></td><td><b>${esc(u.email)}</b></td><td>${esc(u.name||'—')}</td><td>${esc(u.role)}</td><td><span class="badge ${u.status==='ACTIVE'?'badge-success':'badge-danger'}">${esc(u.status)}</span></td><td>${esc(fmt(u.lastLoginAt))}</td></tr>`}).join(''):'<tr><td colspan="6" class="table-empty">No administrator/staff accounts found.</td></tr>';
  $$('#accessTableBody tr[data-email]').forEach(tr=>tr.onclick=e=>{if(e.target.matches('input[type=checkbox]'))return;state.selectedAccessEmail=tr.dataset.email;renderAccess()});$$('.access-select-check').forEach(c=>c.onchange=()=>{state.selectedAccessEmail=c.checked?c.dataset.email:'';renderAccess()});
  const u=state.accessUsers.find(x=>x.email===state.selectedAccessEmail);if(!u){$('#selectedAccessBar').innerHTML='<b>No account selected</b><span>Select an account to enable, disable or delete it.</span>';$('#toggleAccessBtn').disabled=true;$('#deleteAccessBtn').disabled=true;return}
  $('#selectedAccessBar').innerHTML=`<b>${esc(u.name||u.email)}</b><span>${esc(u.email)} • ${esc(u.role)} • ${esc(u.status)}</span>`;
  const protectedAccount=u.email===state.user.email||u.email===cfg.PRIMARY_ADMIN_EMAIL;$('#toggleAccessBtn').disabled=protectedAccount;$('#deleteAccessBtn').disabled=protectedAccount;$('#toggleAccessBtn').textContent=u.status==='ACTIVE'?'Disable selected':'Enable selected';
}
async function toggleAccess(){const u=state.accessUsers.find(x=>x.email===state.selectedAccessEmail);if(!u)return;const b=$('#toggleAccessBtn');busy(b,true,'Updating…');try{const r=await call('setAccessStatus',{email:u.email,enabled:u.status!=='ACTIVE'});const i=state.accessUsers.findIndex(x=>x.email===u.email);if(i>=0)state.accessUsers[i]=r.user;renderAccess();toast(`Access ${r.user.status==='ACTIVE'?'enabled':'disabled'}.`,'success')}catch(e){toast(e.message,'error')}finally{busy(b,false)}}
async function deleteAccess(){const u=state.accessUsers.find(x=>x.email===state.selectedAccessEmail);if(!u)return;const ok=await confirmAction('Delete authorized account',`Delete ${u.role} access for ${u.email}? The login will be removed while audit history remains.`, 'Delete account');if(!ok)return;const b=$('#deleteAccessBtn');busy(b,true,'Deleting…');try{await call('deleteAccessUser',{email:u.email});state.accessUsers=state.accessUsers.filter(x=>x.email!==u.email);state.selectedAccessEmail='';renderAccess();toast('Authorized account deleted.','success')}catch(e){toast(e.message,'error')}finally{busy(b,false)}}
async function loadMailDiagnostics(){try{const r=await call('mailDiagnostics');state.mailDiagnostics=r;$('#mailHealthStatus').textContent=r.status||'UNKNOWN';$('#mailHealthStatus').className=r.status==='READY'?'status-ready':(r.status==='QUOTA_EXHAUSTED'?'status-problem':'status-warning');$('#mailEffectiveSender').textContent=r.effectiveUser||'—';$('#mailRequiredSender').textContent=r.requiredSender||'—';$('#mailQuota').textContent=r.remainingDailyQuota==null?'Unavailable':String(r.remainingDailyQuota);$('#mailTestEmail').value=$('#mailTestEmail').value||state.user?.email||'';const ok=r.status==='READY';setInlineMessage('mailHealthMessage',ok?'Mail environment is ready. Send a test email to verify end-to-end delivery.':(r.status==='SENDER_MISMATCH'?`Apps Script is executing as ${r.effectiveUser}. Redeploy from ${r.requiredSender} if INCENTIFY must be the sender.`:'Mail quota is exhausted or unavailable.'),ok?'success':(r.status==='QUOTA_EXHAUSTED'?'error':'warn'))}catch(e){setInlineMessage('mailHealthMessage',e.message,'error')}}
async function sendTestMail(){const b=$('#sendTestMailBtn'),email=$('#mailTestEmail').value.trim();if(!email){setInlineMessage('mailHealthMessage','Enter a test recipient email.','error');return}busy(b,true,'Sending…');try{const r=await call('sendTestEmail',{email},45000);setInlineMessage('mailHealthMessage',`Test email sent to ${r.target}. Remaining quota: ${r.remainingDailyQuota??'unknown'}.`,'success');toast('Test email sent.','success');void loadMailDiagnostics()}catch(e){setInlineMessage('mailHealthMessage',e.message,'error')}finally{busy(b,false)}}
async function loadMailLog(){try{const r=await call('listMailLog',{limit:50});state.mailLog=r.mailLog||[];renderMailLog()}catch(e){setInlineMessage('mailHealthMessage',e.message,'error')}}
function renderMailLog(){$('#mailLogBody').innerHTML=state.mailLog.length?state.mailLog.map(m=>`<tr><td>${esc(fmt(m.timestamp))}</td><td>${esc(m.type||'—')}</td><td>${esc(m.toEmail||'—')}</td><td><span class="badge ${m.status==='SENT'?'badge-success':'badge-danger'}">${esc(m.status||'—')}</span></td><td class="mail-error-cell">${esc(m.error||'—')}</td></tr>`).join(''):'<tr><td colspan="5" class="table-empty">No email attempts have been logged yet.</td></tr>'}
async function loadSystemRuns(){try{const r=await call('listSystemRuns',{limit:50});state.systemRuns=r.runs||[];renderSystemRuns()}catch(e){toast(e.message,'error')}}
function renderSystemRuns(){$('#systemRunsBody').innerHTML=state.systemRuns.length?state.systemRuns.map(r=>`<tr><td>${esc(fmt(r.startedAt))}</td><td><b>${esc(r.functionName)}</b></td><td><span class="badge ${r.status==='SUCCESS'?'badge-success':(r.status==='ERROR'?'badge-danger':'badge-warn')}">${esc(r.status)}</span></td><td>${esc(r.description||'—')}</td></tr>`).join(''):'<tr><td colspan="4" class="table-empty">No application run records yet.</td></tr>'}

function renderSettings(){const s=state.settings;$('#settingCompany').value=s.company_name||cfg.COMPANY;$('#settingDataMode').value=s.data_mode||'production';$('#settingLinkOpen').value=s.attendance_link_open_time||'10:00';$('#settingLinkClose').value=s.attendance_link_close_time||'10:30';$('#settingShiftMinutes').value=s.shift_duration_minutes||'480';$('#settingOfficeLatitude').value=s.office_latitude||'17.4982778';$('#settingOfficeLongitude').value=s.office_longitude||'78.3845000';$('#settingOfficeRadius').value=s.office_radius_meters||'150';$('#settingMaxLocationAccuracy').value=s.max_location_accuracy_meters||'100';$('#settingDailyAttendanceEmail').value=s.daily_attendance_email_enabled||'1';$('#settingAttendanceSender').value=s.attendance_sender_email||'incentifyprivatelimited@gmail.com';$('#settingAttendanceCopy').value=s.attendance_report_copy_email||'';$('#settingEmployeePortalUrl').value=s.employee_portal_url||'';$('#settingAttendanceCaptureUrl').value=s.attendance_capture_url||'';updateMode()}
function updateMode(){const prod=String(state.settings.data_mode||'production')==='production';$('#dataModeBadge').textContent=prod?'PRODUCTION':'TESTING';$('#dataModeBadge').className='badge '+(prod?'badge-success':'badge-warn');$('#attendanceModeNote').textContent=prod?'Production: attendance immutable':'Testing: deletion enabled';$('#attendanceModeNote').className='badge '+(prod?'badge-success':'badge-warn');selection()}
async function saveSettings(){
  const next={company_name:$('#settingCompany').value.trim(),data_mode:$('#settingDataMode').value,attendance_link_open_time:$('#settingLinkOpen').value,attendance_link_close_time:$('#settingLinkClose').value,shift_duration_minutes:$('#settingShiftMinutes').value,office_latitude:$('#settingOfficeLatitude').value.trim(),office_longitude:$('#settingOfficeLongitude').value.trim(),office_radius_meters:$('#settingOfficeRadius').value,max_location_accuracy_meters:$('#settingMaxLocationAccuracy').value,daily_attendance_email_enabled:$('#settingDailyAttendanceEmail').value,attendance_report_copy_email:$('#settingAttendanceCopy').value.trim()};
  if(state.settings.data_mode==='production'&&next.data_mode==='testing'){const ok=await confirmAction('Enable testing mode','Testing mode permits attendance deletion. Production attendance remains immutable unless you explicitly type TESTING.','Enable testing','TESTING');if(!ok){next.data_mode='production';$('#settingDataMode').value='production'}else next.data_mode_confirmation='TESTING'}
  const b=$('#saveSettingsBtn');busy(b,true,'Saving…');try{const r=await call('saveSettings',{settings:next});state.settings=r.settings||next;renderSettings();renderDashboard();toast('Settings saved.','success')}catch(e){toast(e.message,'error')}finally{busy(b,false)}
}
async function reloadAdmin(){const r=await call('bootstrapAdmin');state.settings=r.settings||{};state.dashboard=r.dashboard||{};state.employees=r.employees||[];state.holidays=r.holidays||[];state.exceptions=r.exceptions||[];state.workday=r.workday||null;renderAll()}
async function reloadDashboard(){const r=await call('dashboard');state.dashboard=r.dashboard||{};renderDashboard()}
init();