const cfg=window.INCENTIFY_EMS_CONFIG,api=window.incentifyEmsApi,$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={token:sessionStorage.getItem(cfg.SESSION_KEY)||'',user:null,settings:{},dashboard:{},employees:[],attendance:[],holidays:[],exceptions:[],accessUsers:[],selectedEmployee:null,selectedPunchIds:new Set(),selectedAccessEmail:'',calendarMonth:new Date(new Date().getFullYear(),new Date().getMonth(),1),workday:null};
const pageMeta={dashboard:['WORKFORCE OVERVIEW','Dashboard'],employees:['EMPLOYEE MANAGEMENT','Employees'],attendance:['ATTENDANCE MANAGEMENT','Attendance'],schedule:['CALENDAR & EXCEPTIONS','Schedule'],reports:['REPORTING & BACKUP','Reports'],access:['ACCESS CONTROL','Portal Access'],settings:['SYSTEM CONTROL','Settings']};
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=v=>{if(!v)return'—';const d=new Date(v);return isNaN(d)?String(v):d.toLocaleString();};
const fmtTime=v=>{if(!v)return'—';const d=new Date(v);return isNaN(d)?String(v):d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});};
const todayKey=()=>{const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const userAgent=()=>navigator.userAgent.slice(0,480);
const call=(action,payload={},timeout)=>api.call(action,{token:state.token,...payload},timeout);
function toast(m,t='info',ms=4200){const e=document.createElement('div');e.className='toast '+t;e.textContent=m;$('#toastStack').appendChild(e);setTimeout(()=>e.remove(),ms)}
function busy(b,on,label){if(!b)return;if(on){b.dataset.old=b.textContent;b.disabled=true;b.textContent=label||'Working…'}else{b.disabled=false;b.textContent=b.dataset.old||b.textContent}}
function clearSession(){state.token='';sessionStorage.removeItem(cfg.SESSION_KEY);sessionStorage.removeItem(cfg.USER_KEY)}
async function init(){bind();const t=todayKey();$('#attendanceStart').value=t;$('#attendanceEnd').value=t;$('#concessionDate').value=t;if(!state.token){location.replace('./index.html');return}try{const r=await call('bootstrapAdmin');if(r.user&&r.user.portal==='employee'){location.replace('./employee.html');return}$('#backendState').textContent='Online';if(r.serverMs!=null)$('#backendState').title=`Backend processing: ${r.serverMs} ms`;state.user=r.user;state.settings=r.settings||{};state.dashboard=r.dashboard||{};state.employees=r.employees||[];state.accessUsers=[];state.holidays=r.holidays||[];state.exceptions=r.exceptions||[];state.workday=r.workday||null;renderAll();navigate('dashboard')}catch(e){clearSession();alert(e.message);location.replace('./index.html')}}
function bind(){
 $('#logoutBtn').onclick=logout;$('#menuBtn').onclick=()=>$('.sidebar').classList.toggle('open');$$('.nav-item').forEach(b=>b.onclick=()=>navigate(b.dataset.page));$$('[data-page-jump]').forEach(b=>b.onclick=()=>navigate(b.dataset.pageJump));
 $('#addEmployeeBtn').onclick=()=>openEmployee(null);$('#editEmployeeBtn').onclick=()=>state.selectedEmployee&&openEmployee(state.selectedEmployee);$('#saveEmployeeBtn').onclick=saveEmployee;$('#employeeSearch').oninput=renderEmployees;$('#deleteEmployeeBtn').onclick=deleteEmployee;$('#sendEnrollmentBtn').onclick=sendEnrollment;$('#resendAttendanceBtn').onclick=resendAttendance;
 $('#applyAttendanceFilters').onclick=loadAttendance;$('#selectAllAttendance').onchange=toggleAll;$('#deleteSelectedAttendance').onclick=deleteAttendance;
 $('#calendarPrev').onclick=()=>{state.calendarMonth=new Date(state.calendarMonth.getFullYear(),state.calendarMonth.getMonth()-1,1);renderCalendar()};$('#calendarNext').onclick=()=>{state.calendarMonth=new Date(state.calendarMonth.getFullYear(),state.calendarMonth.getMonth()+1,1);renderCalendar()};$('#saveHolidayBtn').onclick=saveHoliday;$('#issueConcessionBtn').onclick=issueConcession;
 $('#exportXlsxBtn').onclick=exportXlsx;$('#cloudBackupBtn').onclick=cloudBackup;$('#createAccessUserBtn').onclick=createAccessUser;$('#toggleAccessBtn').onclick=toggleAccess;$('#saveSettingsBtn').onclick=saveSettings;
}
async function logout(){try{await api.call('logout',{token:state.token,userAgent:userAgent()})}catch(_){}clearSession();location.replace('./index.html')}
function navigate(p){if(!pageMeta[p])return;$$('.page').forEach(x=>x.classList.toggle('active-page',x.id===`page-${p}`));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===p));$('#pageEyebrow').textContent=pageMeta[p][0];$('#pageTitle').textContent=pageMeta[p][1];$('.sidebar').classList.remove('open');if(p==='attendance')loadAttendance();if(p==='access')loadAccess();if(p==='schedule')refreshSchedule()}
function renderAll(){renderUser();renderDashboard();renderEmployees();renderSettings();renderAccess();renderCalendar();renderHolidayTable();renderExceptions();populateEmployees()}
function renderUser(){const u=state.user||{};$('#userName').textContent=u.name||u.email||'Admin';$('#userRole').textContent=u.role||'—';$('#userInitial').textContent=(u.name||u.email||'I')[0].toUpperCase()}
function renderDashboard(){const d=state.dashboard||{},s=state.settings||{};$('#metricTotal').textContent=d.totalEmployees||0;$('#metricPresent').textContent=d.presentToday||0;$('#metricAbsent').textContent=d.absentToday||0;$('#metricIn').textContent=d.currentlyIn||0;$('#metricPunches').textContent=d.punchesToday||0;$('#navEmployeeCount').textContent=d.totalEmployees||0;$('#navAttendanceCount').textContent=d.punchesToday||0;$('#dashLinkWindow').textContent=`${s.attendance_link_open_time||'10:00'}–${s.attendance_link_close_time||'10:30'} IST`;$('#dashShiftHours').textContent=`${(Number(s.shift_duration_minutes||480)/60).toFixed(Number(s.shift_duration_minutes||480)%60?1:0)} hours`;$('#dashOfficeRadius').textContent=`${s.office_radius_meters||150} m`;const next=state.holidays.filter(h=>h.date>=todayKey()).sort((a,b)=>a.date.localeCompare(b.date))[0];$('#dashNextHoliday').textContent=next?`${next.date} • ${next.name}`:'No custom holiday scheduled';const w=state.workday||{};$('#todayWorkdayBadge').textContent=w.isWorkday?'WORKDAY':(w.isSunday?'SUNDAY':'HOLIDAY');$('#todayWorkdayBadge').className='badge '+(w.isWorkday?'badge-success':'badge-warn');$('#todayWorkdayMessage').textContent=w.isWorkday?'10 AM attendance links are enabled today.':(w.isSunday?'Sunday is automatically closed. No attendance email is sent.':`Closed: ${w.holiday?.name||'Holiday'}. No attendance email is sent.`);const rows=d.recent||[];$('#recentActivity').classList.toggle('empty-state',!rows.length);$('#recentActivity').innerHTML=rows.length?rows.map(p=>`<div class="activity-item"><span class="punch-dot ${p.punchType==='IN'?'punch-in':'punch-out'}">${esc(p.punchType)}</span><div><b>${esc(p.fullName)}</b><small>${esc(p.employeeCode)} • ${esc(p.source||'')}</small></div><small>${esc(fmtTime(p.punchTime))}</small></div>`).join(''):'No attendance records yet.';updateMode()}
function renderEmployees(){const q=$('#employeeSearch').value.trim().toLowerCase(),rows=!q?state.employees:state.employees.filter(e=>[e.employeeCode,e.fullName,e.email,e.department,e.designation].join(' ').toLowerCase().includes(q));$('#employeeTableBody').innerHTML=rows.map(e=>`<tr data-code="${esc(e.employeeCode)}" class="${state.selectedEmployee?.employeeCode===e.employeeCode?'selected':''}"><td><b>${esc(e.employeeCode)}</b></td><td>${esc(e.fullName)}</td><td>${esc(e.email||'—')}</td><td>${esc(e.department||'—')}</td><td>${esc(e.designation||'—')}</td><td><span class="badge ${e.status==='Active'?'badge-success':'badge-neutral'}">${esc(e.status)}</span></td></tr>`).join('');$$('#employeeTableBody tr').forEach(tr=>tr.onclick=()=>selectEmployee(tr.dataset.code))}
function selectEmployee(code){state.selectedEmployee=state.employees.find(e=>e.employeeCode===code)||null;renderEmployees();const e=state.selectedEmployee;if(!e)return;$('#selectedEmployeeBar').innerHTML=`<b>${esc(e.fullName)} • ${esc(e.employeeCode)}</b><span>${esc(e.email||'No email')} • ${esc(e.department||'—')}</span>`;['editEmployeeBtn','deleteEmployeeBtn','sendEnrollmentBtn','resendAttendanceBtn'].forEach(id=>$('#'+id).disabled=false)}
function openEmployee(e){$('#employeeDialogTitle').textContent=e?'Edit employee':'Add employee';$('#employeeCode').value=e?.employeeCode||'';$('#employeeFullName').value=e?.fullName||'';$('#employeeEmail').value=e?.email||'';$('#employeeMobile').value=e?.mobile||'';$('#employeeDepartment').value=e?.department||'';$('#employeeDesignation').value=e?.designation||'';$('#employeeBranch').value=e?.branch||'';$('#employeeJoiningDate').value=e?.joiningDate||'';$('#employeeShift').value=e?.shiftName||'General';$('#employeeStatus').value=e?.status||'Active';$('#employeeEmergency').value=e?.emergencyContact||'';$('#employeeAddress').value=e?.address||'';$('#employeeNotes').value=e?.notes||'';$('#employeeDialog').showModal()}
function employeePayload(){return{employeeCode:$('#employeeCode').value,fullName:$('#employeeFullName').value.trim(),email:$('#employeeEmail').value.trim(),mobile:$('#employeeMobile').value.trim(),department:$('#employeeDepartment').value.trim(),designation:$('#employeeDesignation').value.trim(),branch:$('#employeeBranch').value.trim(),joiningDate:$('#employeeJoiningDate').value,shiftName:$('#employeeShift').value.trim(),status:$('#employeeStatus').value,emergencyContact:$('#employeeEmergency').value.trim(),address:$('#employeeAddress').value.trim(),notes:$('#employeeNotes').value.trim()}}
async function saveEmployee(){const d=employeePayload(),btn=$('#saveEmployeeBtn');if(!d.fullName){toast('Employee name is required.','error');return}busy(btn,true,'Saving…');try{const a=d.employeeCode?'updateEmployee':'createEmployee';await call(a,{employee:d});$('#employeeDialog').close();await reloadAdmin();toast('Employee saved.','success')}catch(e){toast(e.message,'error')}finally{busy(btn,false)}}
async function deleteEmployee(){const e=state.selectedEmployee;if(!e||!confirm(`Delete/archive ${e.fullName}? Attendance history will be retained.`))return;try{await call('deleteEmployee',{employeeCode:e.employeeCode});state.selectedEmployee=null;await reloadAdmin();toast('Employee archived.','success')}catch(x){toast(x.message,'error')}}
async function sendEnrollment(){const e=state.selectedEmployee;if(!e)return;const b=$('#sendEnrollmentBtn');busy(b,true,'Sending…');try{await call('sendEnrollmentLink',{employeeCode:e.employeeCode});toast('Secure enrollment link emailed.','success')}catch(x){toast(x.message,'error')}finally{busy(b,false)}}
async function resendAttendance(){const e=state.selectedEmployee;if(!e)return;const b=$('#resendAttendanceBtn');busy(b,true,'Sending…');try{const r=await call('resendTodayAttendanceLink',{employeeCode:e.employeeCode});toast(`Attendance link sent. Expires ${fmtTime(r.validUntil)}.`,'success')}catch(x){toast(x.message,'error')}finally{busy(b,false)}}
function populateEmployees(){const opts=state.employees.filter(e=>e.status==='Active').map(e=>`<option value="${esc(e.employeeCode)}">${esc(e.employeeCode)} • ${esc(e.fullName)}</option>`).join('');$('#attendanceEmployee').innerHTML='<option value="">All employees</option>'+opts;$('#concessionEmployee').innerHTML='<option value="">Select employee</option>'+opts}
function filters(){return{startDate:$('#attendanceStart').value,endDate:$('#attendanceEnd').value,employeeCode:$('#attendanceEmployee').value}}
async function loadAttendance(){try{const r=await call('listAttendance',{filters:filters()});state.attendance=r.attendance||[];state.selectedPunchIds.clear();renderAttendance()}catch(e){toast(e.message,'error')}}
function renderAttendance(){$('#attendanceTableBody').innerHTML=state.attendance.map(p=>`<tr><td class="center"><input class="attendance-check" type="checkbox" data-id="${esc(p.id)}"></td><td><b>${esc(p.fullName)}</b><br><small>${esc(p.employeeCode)}</small></td><td><span class="badge ${p.punchType==='IN'?'badge-success':'badge-neutral'}">${esc(p.punchType)}</span></td><td>${esc(fmt(p.punchTime))}</td><td>${esc(p.requiredOutAt?fmt(p.requiredOutAt):'—')}</td><td>${esc(p.source||p.method||'—')}</td><td>${p.distanceMeters==null?'—':esc(p.distanceMeters+' m')}</td></tr>`).join('');$$('.attendance-check').forEach(c=>c.onchange=()=>{c.checked?state.selectedPunchIds.add(c.dataset.id):state.selectedPunchIds.delete(c.dataset.id);selection()});$('#selectAllAttendance').checked=false;selection()}
function toggleAll(e){state.selectedPunchIds.clear();$$('.attendance-check').forEach(c=>{c.checked=e.target.checked;if(c.checked)state.selectedPunchIds.add(c.dataset.id)});selection()}
function selection(){const n=state.selectedPunchIds.size;$('#attendanceSelectionCount').textContent=`${n} selected`;$('#deleteSelectedAttendance').disabled=!n||String(state.settings.data_mode||'production')!=='testing'}
async function deleteAttendance(){if(prompt('Type DELETE to remove selected TEST records.')!=='DELETE')return;try{await call('deleteAttendance',{punchIds:[...state.selectedPunchIds],reason:'V17 testing cleanup'});await loadAttendance();await reloadDashboard();toast('Attendance deleted.','success')}catch(e){toast(e.message,'error')}}
function renderCalendar(){const d=state.calendarMonth,y=d.getFullYear(),m=d.getMonth();$('#calendarTitle').textContent=d.toLocaleString([],{month:'long',year:'numeric'});const first=new Date(y,m,1),days=new Date(y,m+1,0).getDate(),offset=first.getDay(),today=todayKey();let html=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=>`<div class="calendar-weekday">${x}</div>`).join('');for(let i=0;i<offset;i++)html+='<div class="calendar-day empty"></div>';for(let day=1;day<=days;day++){const key=`${y}-${String(m+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`,date=new Date(y,m,day),sun=date.getDay()===0,h=state.holidays.find(x=>x.date===key);html+=`<div class="calendar-day ${sun?'sunday':''} ${h?'custom-holiday':''} ${key===today?'today':''}"><b>${day}</b>${sun?'<small>Sunday</small>':''}${h?`<small>${esc(h.name)}</small>`:''}</div>`}$('#holidayCalendar').innerHTML=html}
function renderHolidayTable(){$('#holidayTableBody').innerHTML=state.holidays.map(h=>`<tr><td>${esc(h.date)}</td><td><b>${esc(h.name)}</b><br><small>${esc(h.notes||'')}</small></td><td>${esc(h.type)}</td><td><button class="btn btn-ghost holiday-delete" data-id="${esc(h.holidayId)}">Remove</button></td></tr>`).join('');$$('.holiday-delete').forEach(b=>b.onclick=()=>removeHoliday(b.dataset.id))}
async function saveHoliday(){const b=$('#saveHolidayBtn'),holiday={date:$('#holidayDate').value,name:$('#holidayName').value.trim(),type:$('#holidayType').value,notes:$('#holidayNotes').value.trim()};busy(b,true,'Saving…');try{await call('saveHoliday',{holiday});$('#holidayName').value='';$('#holidayNotes').value='';await refreshSchedule();toast('Holiday added.','success')}catch(e){toast(e.message,'error')}finally{busy(b,false)}}
async function removeHoliday(id){if(!confirm('Remove this holiday?'))return;try{await call('deleteHoliday',{holidayId:id});await refreshSchedule();toast('Holiday removed.','success')}catch(e){toast(e.message,'error')}}
function renderExceptions(){const by=Object.fromEntries(state.employees.map(e=>[e.employeeCode,e.fullName]));$('#exceptionTableBody').innerHTML=state.exceptions.map(x=>`<tr><td>${esc(by[x.employeeCode]||x.employeeCode)}</td><td>${esc(x.date)}</td><td>${esc(fmtTime(x.validUntil))}</td><td>${esc(x.reason)}</td><td><span class="badge ${x.status==='USED'?'badge-success':'badge-neutral'}">${esc(x.status)}</span></td></tr>`).join('')}
async function issueConcession(){const exception={employeeCode:$('#concessionEmployee').value,date:$('#concessionDate').value,validUntilTime:$('#concessionUntil').value,reason:$('#concessionReason').value.trim()},b=$('#issueConcessionBtn');busy(b,true,'Sending…');try{const r=await call('createLateConcession',{exception});$('#concessionReason').value='';await refreshSchedule();toast(`Late link emailed. Valid until ${fmtTime(r.validUntil)}.`,'success')}catch(e){toast(e.message,'error')}finally{busy(b,false)}}
async function refreshSchedule(){try{const [h,x]=await Promise.all([call('listHolidays'),call('listAttendanceExceptions')]);state.holidays=h.holidays||[];state.exceptions=x.exceptions||[];renderCalendar();renderHolidayTable();renderExceptions();renderDashboard()}catch(e){toast(e.message,'error')}}
async function exportXlsx(){const b=$('#exportXlsxBtn');busy(b,true,'Generating…');try{const r=await call('exportAttendanceXlsx',{filters:filters()},90000);$('#exportStatus').textContent=`${r.count} records • ${r.filename}`;window.open(r.fileUrl,'_blank','noopener')}catch(e){toast(e.message,'error')}finally{busy(b,false)}}
async function cloudBackup(){const b=$('#cloudBackupBtn');busy(b,true,'Creating…');try{const r=await call('createCloudBackup',{},90000);$('#backupStatus').textContent=r.filename;window.open(r.fileUrl,'_blank','noopener')}catch(e){toast(e.message,'error')}finally{busy(b,false)}}
async function loadAccess(){try{const r=await call('listAccessUsers');state.accessUsers=r.users||[];renderAccess();if(r.serverMs!=null)$('#backendState').title=`Last backend processing: ${r.serverMs} ms`}catch(e){toast(e.message,'error')}}
async function createAccessUser(){const b=$('#createAccessUserBtn'),account={name:$('#accessNewName').value.trim(),email:$('#accessNewEmail').value.trim(),role:$('#accessNewRole').value};if(!account.name){toast('Administrator name is required.','error');return}if(!account.email){toast('Administrator email is required.','error');return}busy(b,true,'Adding…');try{const r=await call('createAccessUser',{account});$('#accessNewName').value='';$('#accessNewEmail').value='';$('#accessNewRole').value='ADMIN';await loadAccess();toast(`${r.created?'Authorized account added':'Authorized account updated'}: ${r.user.email}`,'success')}catch(e){toast(e.message,'error')}finally{busy(b,false)}}
function renderAccess(){$('#accessTableBody').innerHTML=state.accessUsers.map(u=>`<tr data-email="${esc(u.email)}" class="${state.selectedAccessEmail===u.email?'selected':''}"><td><b>${esc(u.email)}</b></td><td>${esc(u.name||'—')}</td><td>${esc(u.role)}</td><td>${esc(u.employeeCode||'—')}</td><td><span class="badge ${u.status==='ACTIVE'?'badge-success':'badge-danger'}">${esc(u.status)}</span></td><td>${esc(fmt(u.lastLoginAt))}</td></tr>`).join('');$$('#accessTableBody tr').forEach(tr=>tr.onclick=()=>{state.selectedAccessEmail=tr.dataset.email;renderAccess();const u=state.accessUsers.find(x=>x.email===state.selectedAccessEmail);$('#selectedAccessBar').innerHTML=`<b>${esc(u.name||u.email)}</b><span>${esc(u.email)} • ${esc(u.status)}</span>`;$('#toggleAccessBtn').disabled=u.role==='ADMIN'&&u.email===state.user.email;$('#toggleAccessBtn').textContent=u.status==='ACTIVE'?'Disable selected access':'Enable selected access'})}
async function toggleAccess(){const u=state.accessUsers.find(x=>x.email===state.selectedAccessEmail);if(!u)return;try{await call('setAccessStatus',{email:u.email,enabled:u.status!=='ACTIVE'});await loadAccess();toast('Access updated.','success')}catch(e){toast(e.message,'error')}}
function renderSettings(){const s=state.settings;$('#settingCompany').value=s.company_name||cfg.COMPANY;$('#settingDataMode').value=s.data_mode||'production';$('#settingLinkOpen').value=s.attendance_link_open_time||'10:00';$('#settingLinkClose').value=s.attendance_link_close_time||'10:30';$('#settingShiftMinutes').value=s.shift_duration_minutes||'480';$('#settingOfficeLatitude').value=s.office_latitude||'17.4983333';$('#settingOfficeLongitude').value=s.office_longitude||'78.3843889';$('#settingOfficeRadius').value=s.office_radius_meters||'150';$('#settingMaxLocationAccuracy').value=s.max_location_accuracy_meters||'100';$('#settingDailyAttendanceEmail').value=s.daily_attendance_email_enabled||'1';$('#settingAttendanceSender').value=s.attendance_sender_email||'incentifyprivatelimited@gmail.com';$('#settingAttendanceCopy').value=s.attendance_report_copy_email||'';$('#settingEmployeePortalUrl').value=s.employee_portal_url||'';$('#settingAttendanceCaptureUrl').value=s.attendance_capture_url||'';updateMode()}
function updateMode(){const prod=String(state.settings.data_mode||'production')==='production';$('#dataModeBadge').textContent=prod?'PRODUCTION':'TESTING';$('#dataModeBadge').className='badge '+(prod?'badge-success':'badge-warn');$('#attendanceModeNote').textContent=prod?'Production: attendance immutable':'Testing: deletion enabled';$('#attendanceModeNote').className='badge '+(prod?'badge-success':'badge-warn');selection()}
async function saveSettings(){const next={company_name:$('#settingCompany').value.trim(),data_mode:$('#settingDataMode').value,attendance_link_open_time:$('#settingLinkOpen').value,attendance_link_close_time:$('#settingLinkClose').value,shift_duration_minutes:$('#settingShiftMinutes').value,office_latitude:$('#settingOfficeLatitude').value.trim(),office_longitude:$('#settingOfficeLongitude').value.trim(),office_radius_meters:$('#settingOfficeRadius').value,max_location_accuracy_meters:$('#settingMaxLocationAccuracy').value,daily_attendance_email_enabled:$('#settingDailyAttendanceEmail').value,attendance_report_copy_email:$('#settingAttendanceCopy').value.trim(),employee_portal_url:$('#settingEmployeePortalUrl').value.trim(),attendance_capture_url:$('#settingAttendanceCaptureUrl').value.trim()};if(state.settings.data_mode==='production'&&next.data_mode==='testing'){const p=prompt('Type TESTING to enable deletion.');if(p!=='TESTING'){next.data_mode='production';$('#settingDataMode').value='production'}else next.data_mode_confirmation='TESTING'}const b=$('#saveSettingsBtn');busy(b,true,'Saving…');try{const r=await call('saveSettings',{settings:next});state.settings=r.settings||next;renderSettings();renderDashboard();toast('Settings saved.','success')}catch(e){toast(e.message,'error')}finally{busy(b,false)}}
async function reloadAdmin(){const r=await call('bootstrapAdmin');state.settings=r.settings||{};state.dashboard=r.dashboard||{};state.employees=r.employees||[];state.accessUsers=r.accessUsers||[];state.holidays=r.holidays||[];state.exceptions=r.exceptions||[];state.workday=r.workday||null;renderAll();await loadAttendance()}
async function reloadDashboard(){const r=await call('dashboard');state.dashboard=r.dashboard||{};renderDashboard()}
init();