const cfg=window.INCENTIFY_EMS_CONFIG,api=window.incentifyEmsApi,$=(s,r=document)=>r.querySelector(s);
const token=new URLSearchParams(location.search).get('token')||'';
const state={context:null,location:null,models:false,stream:null};
function toast(m,t='info',ms=4200){const e=document.createElement('div');e.className='toast '+t;e.textContent=m;$('#toastStack').appendChild(e);setTimeout(()=>e.remove(),ms)}
function busy(b,on,label){if(on){b.dataset.old=b.textContent;b.disabled=true;b.textContent=label}else{b.disabled=false;b.textContent=b.dataset.old||b.textContent}}
function status(title,text,type=''){$('#linkStatusTitle').textContent=title;$('#linkStatusText').textContent=text;$('#linkStatusBox').className='portal-notice '+type}
const fmt=v=>{const d=new Date(v);return isNaN(d)?String(v):d.toLocaleString([], {dateStyle:'medium',timeStyle:'short'})};
async function init(){
  if(!token){status('Invalid link','The attendance token is missing.','error');return}
  try{
    const r=await api.call('getAttendanceLinkContext',{attendanceToken:token},20000);state.context=r;
    if(r.state==='USED'){
      const done=r.completedResult||null;
      if(done&&done.action==='ENROLLED'){$('#captureContent').classList.add('hidden');$('#linkSuccess').classList.remove('hidden');$('#linkSuccessTitle').textContent='Face enrollment already completed';$('#linkSuccessText').textContent='Your face enrollment was saved successfully. No recapture is required.';status('Completed','The server confirmed this enrollment was already completed.','success');return}
      if(done&&done.action==='IN'){$('#captureContent').classList.add('hidden');$('#linkSuccess').classList.remove('hidden');$('#linkSuccessTitle').textContent='Attendance already recorded';$('#linkSuccessText').textContent=done.punch&&done.punch.requiredOutAt?`Your IN attendance is recorded. Earliest checkout: ${fmt(done.punch.requiredOutAt)}.`:'Your IN attendance was recorded successfully.';status('Completed','The server confirmed this attendance link was already completed.','success');return}
      status('Link already used',r.message||'This link has already been used.','success');return
    }
    $('#captureContent').classList.remove('hidden');$('#linkEmployeeName').textContent=r.employee.fullName;$('#linkEmployeeCode').textContent=r.employee.employeeCode;$('#linkDate').textContent=r.date;$('#linkExpiry').textContent=fmt(r.validUntil);
    status(r.linkType==='ENROLL'?'Face enrollment link':'Attendance link',r.linkType==='ENROLL'?'Verify your office location and capture your face for future attendance.':'This link is active. Complete location and face verification before it expires.','success');
    $('#linkCheckLocationBtn').onclick=checkLocation;$('#linkCaptureBtn').onclick=captureAndSubmit;const warm=()=>models().catch(()=>{});if('requestIdleCallback'in window)requestIdleCallback(warm,{timeout:1200});else setTimeout(warm,350);
  }catch(e){status('Attendance link unavailable',e.message,'error')}
}
function preciseLocation(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error('Location is not supported by this browser.'));navigator.geolocation.getCurrentPosition(p=>resolve({latitude:Number(p.coords.latitude),longitude:Number(p.coords.longitude),accuracy:Number(p.coords.accuracy),capturedAt:new Date().toISOString()}),e=>reject(new Error(e.code===1?'Allow precise location to continue.':(e.message||'Could not read your location.'))),{enableHighAccuracy:true,timeout:15000,maximumAge:0})})}
async function checkLocation(){const b=$('#linkCheckLocationBtn');busy(b,true,'Locating…');try{state.location=await preciseLocation();$('#linkLocationState').textContent='Location captured';$('#linkLocationDetail').textContent=`Accuracy ±${Math.round(state.location.accuracy)} m. Final office-radius validation happens on the server when attendance is submitted.`;toast('Location captured.','success');return state.location}catch(e){state.location=null;$('#linkLocationState').textContent='Location blocked';$('#linkLocationDetail').textContent=e.message;toast(e.message,'error');throw e}finally{busy(b,false)}}
async function models(){if(state.models)return;if(!window.faceapi){await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=cfg.FACE_LIBRARY_URL;s.onload=resolve;s.onerror=()=>reject(new Error('Face verification library could not load.'));document.head.appendChild(s)})}await Promise.all([faceapi.nets.tinyFaceDetector.loadFromUri(cfg.FACE_MODEL_URL),faceapi.nets.faceLandmark68Net.loadFromUri(cfg.FACE_MODEL_URL),faceapi.nets.faceRecognitionNet.loadFromUri(cfg.FACE_MODEL_URL)]);state.models=true}
async function startCamera(){state.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:960},height:{ideal:720}},audio:false});const v=$('#linkVideo');v.srcObject=state.stream;await v.play();$('#linkCameraPlaceholder').classList.add('hidden')}
function stopCamera(){if(state.stream){state.stream.getTracks().forEach(t=>t.stop());state.stream=null}$('#linkVideo').srcObject=null;$('#linkCameraPlaceholder').classList.remove('hidden')}
function avg(ds){const out=new Array(ds[0].length).fill(0);ds.forEach(d=>d.forEach((v,i)=>out[i]+=Number(v)));for(let i=0;i<out.length;i++)out[i]/=ds.length;const n=Math.sqrt(out.reduce((s,v)=>s+v*v,0))||1;return out.map(v=>Number((v/n).toFixed(8)))}
async function captureAndSubmit(){const b=$('#linkCaptureBtn');busy(b,true,'Preparing…');try{if(!state.location||Date.now()-new Date(state.location.capturedAt).getTime()>60000)await checkLocation();await models();await startCamera();const video=$('#linkVideo'),samples=[],centres=[];for(let i=0;i<3;i++){let found=null;for(let a=0;a<14&&!found;a++){found=await faceapi.detectSingleFace(video,new faceapi.TinyFaceDetectorOptions({inputSize:224,scoreThreshold:.5})).withFaceLandmarks().withFaceDescriptor();if(!found)await new Promise(r=>setTimeout(r,180))}if(!found)throw new Error('Face not detected clearly. Improve lighting and try again.');samples.push([...found.descriptor]);const box=found.detection.box;centres.push({x:(box.x+box.width/2)/video.videoWidth,y:(box.y+box.height/2)/video.videoHeight});$('#linkCaptureProgress').textContent=`Face sample ${i+1} / 3`;await new Promise(r=>setTimeout(r,350))}
    let movement=0;for(let i=1;i<centres.length;i++){const dx=centres[i].x-centres[i-1].x,dy=centres[i].y-centres[i-1].y;movement+=Math.sqrt(dx*dx+dy*dy)}if(movement<0.012)throw new Error('Liveness check needs a small natural head movement. Move slightly and try again.');
    $('#linkCaptureProgress').textContent=state.context&&state.context.linkType==='ENROLL'?'Saving face securely…':'Recording attendance…';
    stopCamera();
    status('Secure submission in progress','Keep this page open while the encrypted face descriptor is saved. On slower mobile networks this can take a few seconds.');
    const r=await api.call('submitAttendanceLinkFace',{attendanceToken:token,descriptor:avg(samples),livenessPassed:true,location:state.location,deviceName:'Mobile attendance link'},70000);
    $('#captureContent').classList.add('hidden');$('#linkSuccess').classList.remove('hidden');if(r.action==='ENROLLED'){$('#linkSuccessTitle').textContent='Face enrollment completed';$('#linkSuccessText').textContent='Your attendance face was enrolled successfully. Future check-in links will verify against this enrollment.'}else{$('#linkSuccessTitle').textContent='IN attendance recorded';$('#linkSuccessText').textContent=`Checked in at ${fmt(r.punch.punchTime)}. Your earliest checkout is ${fmt(r.punch.requiredOutAt)} after completing the full ${Number(r.punch.shiftMinutes||480)/60}-hour shift.`}status('Completed',r.replayed?'The server recovered the completed submission after a temporary network delay. This secure link is now consumed.':'This secure link has been consumed and cannot be used again.','success')
  }catch(e){stopCamera();$('#linkCaptureProgress').textContent='Ready';const msg=e&&e.message?e.message:'Secure submission could not be confirmed.';status('Submission not confirmed',msg,'error');toast(msg,'error',6500)}finally{busy(b,false)}}
window.addEventListener('beforeunload',stopCamera);init();