const cfg=window.INCENTIFY_EMS_CONFIG,api=window.incentifyEmsApi,$=(s,r=document)=>r.querySelector(s);
const state={token:sessionStorage.getItem(cfg.SESSION_KEY)||'',user:null,employee:null,settings:{},attendance:[],today:{},checkout:{}};
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=v=>{if(!v)return'—';const d=new Date(v);return isNaN(d)?String(v):d.toLocaleString()};
const fmtTime=v=>{if(!v)return'—';const d=new Date(v);return isNaN(d)?String(v):d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})};
const todayKey=()=>{const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const call=(a,p={},t)=>api.call(a,{token:state.token,...p},t);
function toast(m,t='info'){const e=document.createElement('div');e.className='toast '+t;e.textContent=m;$('#toastStack').appendChild(e);setTimeout(()=>e.remove(),4200)}
function busy(b,on,label){if(on){b.dataset.old=b.textContent;b.disabled=true;b.textContent=label}else{b.disabled=false;b.textContent=b.dataset.old||b.textContent}}
function getLocation(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error('Location is not supported by this browser.'));navigator.geolocation.getCurrentPosition(p=>resolve({latitude:Number(p.coords.latitude),longitude:Number(p.coords.longitude),accuracy:Number(p.coords.accuracy),capturedAt:new Date().toISOString()}),e=>reject(new Error(e.code===1?'Allow precise location to check out.':(e.message||'Could not read location.'))),{enableHighAccuracy:true,timeout:15000,maximumAge:0})})}
async function init(){if(!state.token){location.replace('./index.html');return}const t=todayKey();$('#selfAttendanceStart').value=t;$('#selfAttendanceEnd').value=t;$('#employeeLogoutBtn').onclick=logout;$('#selfAttendanceApply').onclick=loadAttendance;$('#checkoutBtn').onclick=checkout;try{await bootstrap();$('#employeeBackendState').textContent='Online';if(state.user&&state.user.portal!=='employee'){location.replace('./admin.html');return}}catch(e){sessionStorage.removeItem(cfg.SESSION_KEY);sessionStorage.removeItem(cfg.USER_KEY);sessionStorage.setItem('incentify_ems_login_flash',e.message||'Your session expired. Please sign in again.');location.replace('./index.html')}}
async function bootstrap(){const r=await call('bootstrapEmployee');state.user=r.user;state.employee=r.employee;state.settings=r.settings||{};state.attendance=r.attendance||[];state.today=r.today||{};state.checkout=r.checkout||{};render()}
function render(){const e=state.employee||{},u=state.user||{};$('#employeeWelcomeName').textContent=`Welcome, ${e.fullName||'Employee'}`;$('#employeeUserName').textContent=e.fullName||u.email||'Employee';$('#employeeUserInitial').textContent=(e.fullName||u.email||'E')[0].toUpperCase();$('#selfEmployeeCode').textContent=e.employeeCode||'—';$('#selfStatus').textContent=e.status||'—';$('#selfName').textContent=e.fullName||'—';$('#selfEmail').textContent=e.email||u.email||'—';$('#selfDepartment').textContent=e.department||'—';$('#selfDesignation').textContent=e.designation||'—';$('#selfBranch').textContent=e.branch||'—';$('#selfShift').textContent=e.shiftName||'—';$('#selfJoining').textContent=e.joiningDate||'—';const mins=Number(state.settings.shift_duration_minutes||480);$('#selfShiftDuration').textContent=mins%60?`${(mins/60).toFixed(1)}h`:`${mins/60}h`;renderToday();renderCheckout();renderAttendance()}
function renderToday(){const t=state.today||{};if(!t.lastPunch){$('#selfTodayStatus').textContent='NOT IN';$('#selfTodayDetail').textContent='Use the secure email attendance link to check in.';return}$('#selfTodayStatus').textContent=t.currentlyIn?'IN':'OUT';$('#selfTodayDetail').textContent=`Last: ${t.lastPunch.punchType} • ${fmtTime(t.lastPunch.punchTime)}`}
function renderCheckout(){const c=state.checkout||{},b=$('#checkoutBtn');$('#checkoutInTime').textContent=fmtTime(c.checkedInAt);$('#checkoutEligibleTime').textContent=fmtTime(c.requiredOutAt);$('#checkoutOutTime').textContent=fmtTime(c.checkedOutAt);$('#checkoutMessage').textContent=c.message||'Waiting for attendance.';$('#selfCheckoutState').textContent=c.state==='READY'?'READY':c.state==='COMPLETED'?'DONE':c.state==='WORKING'?'WORKING':'WAITING';$('#selfCheckoutTime').textContent=c.state==='WORKING'?`${c.remainingMinutes||0} min remaining`:(c.requiredOutAt?`Earliest ${fmtTime(c.requiredOutAt)}`:'Waiting for IN');$('#checkoutBadge').textContent=c.state||'WAITING';$('#checkoutBadge').className='badge '+(c.canCheckout?'badge-success':c.state==='COMPLETED'?'badge-success':'badge-neutral');b.disabled=!c.canCheckout;b.textContent=c.canCheckout?'Check out now':'Checkout locked'}
async function checkout(){const b=$('#checkoutBtn');busy(b,true,'Checking location…');try{const location=await getLocation();const r=await call('checkoutMyAttendance',{location},60000);toast(`OUT recorded at ${fmtTime(r.punch.punchTime)}.`,'success');await bootstrap()}catch(e){toast(e.message,'error')}finally{busy(b,false);renderCheckout()}}
async function loadAttendance(){try{const r=await call('getMyAttendance',{filters:{startDate:$('#selfAttendanceStart').value,endDate:$('#selfAttendanceEnd').value}});state.attendance=r.attendance||[];renderAttendance()}catch(e){toast(e.message,'error')}}
function renderAttendance(){const rows=state.attendance||[];$('#selfAttendanceBody').innerHTML=rows.map(p=>`<tr><td><span class="badge ${p.punchType==='IN'?'badge-success':'badge-neutral'}">${esc(p.punchType)}</span></td><td>${esc(fmt(p.punchTime))}</td><td>${esc(p.requiredOutAt?fmt(p.requiredOutAt):'—')}</td><td>${esc(p.source||p.method||'—')}</td><td>${p.distanceMeters==null?'—':esc(p.distanceMeters+' m')}</td></tr>`).join('');$('#selfAttendanceEmpty').classList.toggle('hidden',rows.length>0)}
async function logout(){try{await api.call('logout',{token:state.token,userAgent:navigator.userAgent.slice(0,480)})}catch(_){}sessionStorage.removeItem(cfg.SESSION_KEY);sessionStorage.removeItem(cfg.USER_KEY);location.replace('./index.html')}
init();