import fs from 'node:fs';
const read=f=>fs.readFileSync(f,'utf8');
const index=read('index.html'),admin=read('admin.html'),employee=read('employee.html'),attendance=read('attendance.html');
const adminJs=read('js/admin.js'),employeeJs=read('js/employee.js'),attendanceJs=read('js/attendance.js'),authJs=read('js/auth.js'),config=read('js/config.js'),api=read('js/api-client.js'),sw=read('sw.js'),workflow=read('.github/workflows/pages.yml'),deployTest=read('scripts/test-v20-deployment.ps1');
const checks=[];const add=(ok,n)=>checks.push({ok:!!ok,n});
add(index.includes('Admin Login')&&index.includes('Employee Login'),'separate admin and employee login choices');
add(admin.includes('HOLIDAY CALENDAR')&&admin.includes('LATE ARRIVAL CONCESSION'),'holiday calendar and late-concession UI exist');
add(!admin.includes('<video')&&!admin.includes('<canvas'),'admin portal contains no face camera');
add(!employee.includes('<video')&&!employee.includes('<canvas'),'employee portal contains no face camera');
add(employee.includes('Complete My Shift')&&employeeJs.includes('checkoutMyAttendance'),'employee 8-hour shift checkout exists');
add(attendance.includes('<video')&&attendanceJs.includes('submitAttendanceLinkFace'),'face verification exists only on secure attendance link');
add(attendanceJs.includes('navigator.geolocation'),'attendance link captures mobile location');
add(admin.includes('id="employeeDialog" class="app-modal"')&&!admin.includes('<dialog id="employeeDialog"'),'employee form uses custom modal');
add(admin.includes('id="cancelEmployeeBtn"')&&adminJs.includes("closeModal('employeeDialog')"),'employee Cancel/X close controls are wired');
add(adminJs.includes("setInlineMessage('employeeFormMessage'")&&admin.includes('id="employeeFormMessage"'),'employee errors render inside employee modal');
add(admin.includes('id="accessDialog" class="app-modal"')&&admin.includes('id="addAccessBtn"'),'dedicated add-access modal exists');
add(admin.includes('id="deleteAccessBtn"')&&adminJs.includes("call('deleteAccessUser'"),'admin/staff delete control is wired');
add(adminJs.includes('cfg.PRIMARY_ADMIN_EMAIL')&&config.includes("PRIMARY_ADMIN_EMAIL: 'incentifyprivatelimited@gmail.com'"),'primary administrator protected in frontend');
add(admin.includes('Mail Health')&&adminJs.includes("call('mailDiagnostics'")&&adminJs.includes("call('sendTestEmail'"),'mail diagnostics/test email exist');
add(admin.includes('Application Run Descriptions')&&adminJs.includes("call('listSystemRuns'"),'backend run descriptions are visible');
add(adminJs.includes('id="confirmPhraseInput"')||admin.includes('id="confirmPhraseInput"'),'typed destructive confirmation UI exists');
add(adminJs.includes("'DELETE'")&&adminJs.includes("'TESTING'"),'attendance deletion/testing-mode confirmations are custom typed confirmations');
add(!/\bprompt\(|\balert\(|\bconfirm\(/.test(adminJs+employeeJs),'browser prompt/alert/confirm calls removed from portals');
add(admin.includes('id="settingEmployeePortalUrl" readonly')&&admin.includes('id="settingAttendanceCaptureUrl" readonly'),'production public URLs are read-only in Admin');
add(config.includes("VERSION: '20.0.0'")&&config.includes("BACKEND_VERSION: '20.0.0'"),'frontend targets V20 backend');
add(config.includes('AKfycbxXvyGi6PCfBMC0Tza9FK_s6P4ii6vRXJlRZR2o1iaJd5Hu00VCCefABW0Tca_kSlM8'),'production Apps Script deployment URL configured');
add(config.includes("SESSION_KEY: 'incentify_ems_v20_session'")&&config.includes("USER_KEY: 'incentify_ems_v20_user'"),'V20 session namespace isolated');
add(api.includes('__incentify_ems_v20_cb_')&&api.includes('_jsonpOnce'),'V20 JSONP callback contract configured');
add(api.includes('requestReplayStatus')&&api.includes('_probeMutation'),'mutation recovery probes persisted backend result');
add(api.includes("'createEmployee','updateEmployee','deleteEmployee','sendEnrollmentLink'")&&api.includes("'createAccessUser','setAccessStatus','deleteAccessUser','sendTestEmail'"),'all critical mutations use replay-safe transport');
add(api.includes('replaySafeMutationActions')&&api.includes('_replaySafeMutationTransport'),'persistent replay transport is enabled');
add(api.includes('inflightSafe')&&api.includes('bootstrapAdmin')&&api.includes('bootstrapEmployee'),'duplicate startup reads are coalesced');
add(!adminJs.includes("api.call('health'")&&!adminJs.includes("api.call('validateSession'"),'admin startup avoids redundant health/session round trips');
add(!employeeJs.includes("api.call('health'")&&!employeeJs.includes("api.call('validateSession'"),'employee startup avoids redundant health/session round trips');
add(!attendanceJs.includes("api.call('health'")&&attendanceJs.includes('requestIdleCallback'),'attendance page avoids redundant health call and prewarms face models');
add(attendanceJs.includes("done&&done.action==='ENROLLED'")&&attendanceJs.includes('completedResult'),'refresh of consumed enrollment link recovers success state');
add(attendance.includes('rel="preconnect" href="https://cdn.jsdelivr.net"'),'face-model CDN preconnect enabled');
add(index.includes('api-client.js?v=20.0.0')&&index.includes('auth.js?v=20.0.0'),'login assets cache-busted');
add(sw.includes('incentify-ems-v20-shell-1')&&sw.includes("url.searchParams.get('v')==='20.0.0'"),'V20 PWA cache isolated');
add(!api.includes('iframe')&&!api.includes('Bridge.html'),'no iframe bridge is used');
add(workflow.includes('verify-v20.mjs')&&workflow.includes('Deploy INCENTIFY EMS V20'),'GitHub Pages verifies V20 before deployment');
add(deployTest.includes('$attempt -le 3')&&deployTest.includes('RECOVERED_TRANSIENTS'),'deployment gate recovers transient Apps Script failures');
add(authJs.includes('incentify_ems_login_flash'),'session errors return to login without blocking alert dialogs');
add(adminJs.includes('state.employees.push(saved)'),'employee save updates local state without full bootstrap reload');
add(adminJs.includes("call('deleteAccessUser'")&&adminJs.includes("call('setAccessStatus'"),'access delete/enable-disable actions are wired');
add(adminJs.includes("call('listMailLog'")&&admin.includes('mailLogBody'),'mail delivery log is visible');
add(attendance.includes('consentIdentity')&&attendance.includes('consentLocation')&&attendance.includes('consentBiometric'),'attendance capture requires three production confirmation checkboxes');
add(attendanceJs.includes('validateAttendanceLocation')&&api.includes("'validateAttendanceLocation','downloadExportChunk'"),'server location pre-validation and secure download APIs configured');
add(attendanceJs.includes('sampleTarget')&&attendanceJs.includes('descriptorSpread')&&attendanceJs.includes('videoBrightness'),'multi-sample face quality capture is implemented');
add(attendanceJs.includes('movement<0.035')&&attendanceJs.includes('activeChallengePassed:true'),'active movement challenge is required');
add(adminJs.includes('employee-select-check')&&adminJs.includes('access-select-check'),'employee and access tables expose explicit selection checkboxes');
add(adminJs.includes('downloadSecureTicket')&&adminJs.includes('downloadExportChunk')&&adminJs.includes('sha256Hex'),'reports and backup use secure direct browser download with integrity check');
add(adminJs.includes("office_latitude||'17.4982778'")&&adminJs.includes("office_longitude||'78.3845000'"),'admin UI defaults use exact production office coordinates');
const failed=checks.filter(x=>!x.ok);for(const c of checks)console.log(`${c.ok?'PASS':'FAIL'}: ${c.n}`);if(failed.length){console.error(`\n${failed.length} frontend verification check(s) failed.`);process.exit(1);}console.log(`\nV20 frontend verification passed: ${checks.length} checks.`);
