import fs from 'node:fs';
const read=f=>fs.readFileSync(f,'utf8');
const index=read('index.html'),admin=read('admin.html'),employee=read('employee.html'),attendance=read('attendance.html');
const adminJs=read('js/admin.js'),employeeJs=read('js/employee.js'),attendanceJs=read('js/attendance.js'),config=read('js/config.js'),api=read('js/api-client.js'),sw=read('sw.js'),workflow=read('.github/workflows/pages.yml'),deployTest=read('scripts/test-v17-deployment.ps1');
const checks=[];const add=(ok,n)=>checks.push({ok:!!ok,n});
add(index.includes('Admin Login')&&index.includes('Employee Login'),'separate admin and employee login choices');
add(admin.includes('HOLIDAY CALENDAR')&&admin.includes('LATE ARRIVAL CONCESSION'),'admin holiday calendar and late-concession UI exist');
add(!admin.includes('<video')&&!admin.includes('<canvas'),'admin portal contains no face camera');
add(!employee.includes('<video')&&!employee.includes('<canvas'),'employee portal contains no face camera');
add(employee.includes('Complete My Shift')&&employeeJs.includes('checkoutMyAttendance'),'employee 8-hour shift checkout exists');
add(attendance.includes('<video')&&attendanceJs.includes('submitAttendanceLinkFace'),'face verification exists only on secure attendance link');
add(attendanceJs.includes('navigator.geolocation'),'attendance link captures mobile location');
add(adminJs.includes('createLateConcession')&&adminJs.includes('saveHoliday'),'admin concessions and holidays exist');
add(config.includes("VERSION: '17.0.0'")&&config.includes("BACKEND_VERSION: '17.0.0'"),'V17 frontend targets stable V17 backend');
add(config.includes('AKfycbxXvyGi6PCfBMC0Tza9FK_s6P4ii6vRXJlRZR2o1iaJd5Hu00VCCefABW0Tca_kSlM8'),'fresh Apps Script deployment URL configured');
add(api.includes('__incentify_ems_v17_cb_')&&api.includes('_jsonpOnce'),'V17 JSONP primary transport uses V17 backend-compatible callback contract');
add(!api.includes('__incentify_ems_v17_1_cb_')&&!api.includes('__incentify_ems_v17_2_cb_'),'frontend does not add release suffix to backend JSONP callback namespace');
const safeBlock=api.slice(api.indexOf('async _safeTransport'),api.indexOf('async _singleDeliveryTransport'));
add(safeBlock.indexOf('this._jsonpOnce')>=0&&safeBlock.indexOf('this._fetchOnce')>safeBlock.indexOf('this._jsonpOnce'),'safe transport prefers JSONP before fetch fallback');
add(api.includes('ems17_')&&api.includes('safeRetryActions'),'V17 logical request IDs and retry policy configured');
add(api.includes('_singleDeliveryTransport')&&api.includes('return this._jsonpOnce'),'unsafe mutations are not automatically replayed');
add(!adminJs.includes("api.call('health'")&&!adminJs.includes("api.call('validateSession'"),'admin startup avoids redundant health/session round trips');
add(!employeeJs.includes("api.call('health'")&&!employeeJs.includes("api.call('validateSession'"),'employee startup avoids redundant health/session round trips');
add(!attendanceJs.includes("api.call('health'")&&attendanceJs.includes('requestIdleCallback'),'attendance page removes redundant health call and prewarms face models');
add(attendance.includes('rel="preconnect" href="https://cdn.jsdelivr.net"'),'face-model CDN preconnect enabled');
add(index.includes('api-client.js?v=17.0.0')&&index.includes('auth.js?v=17.0.0'),'V17 login assets cache-busted');
add(sw.includes('incentify-ems-v17-shell-1')&&sw.includes("url.searchParams.get('v')==='17.0.0'"),'V17 PWA cache isolation and cache-first versioned assets');
add(!api.includes('iframe')&&!api.includes('Bridge.html'),'no iframe bridge is used');
add(workflow.includes('verify-v17.mjs')&&workflow.includes('Deploy INCENTIFY EMS V17'),'GitHub Pages verifies V17 before deploy');
add(deployTest.includes('$attempt -le 3')&&deployTest.includes('RECOVERED_TRANSIENTS'),'deployment gate recovers transient Apps Script 404s before failing');
add(admin.includes('Add Admin / Staff Account')&&adminJs.includes('createAccessUser'),'admin can add ADMIN/HR/MANAGER accounts from portal');
add(adminJs.includes('serverMs')&&adminJs.includes('Backend processing'),'backend processing latency is surfaced for diagnostics');
const failed=checks.filter(x=>!x.ok);for(const c of checks)console.log(`${c.ok?'PASS':'FAIL'}: ${c.n}`);if(failed.length){console.error(`\n${failed.length} frontend verification check(s) failed.`);process.exit(1);}console.log(`\nV17 frontend verification passed: ${checks.length} checks.`);
