import fs from 'node:fs';
const read=f=>fs.readFileSync(f,'utf8');
const index=read('index.html'),admin=read('admin.html'),employee=read('employee.html'),attendance=read('attendance.html');
const adminJs=read('js/admin.js'),employeeJs=read('js/employee.js'),attendanceJs=read('js/attendance.js'),config=read('js/config.js'),api=read('js/api-client.js'),sw=read('sw.js'),workflow=read('.github/workflows/pages.yml'),deployTest=read('scripts/test-v18-deployment.ps1');
const checks=[];const add=(ok,n)=>checks.push({ok:!!ok,n});
add(index.includes('Admin Login')&&index.includes('Employee Login'),'separate admin and employee login choices');
add(admin.includes('HOLIDAY CALENDAR')&&admin.includes('LATE ARRIVAL CONCESSION'),'holiday calendar and late-concession UI exist');
add(!admin.includes('<video')&&!admin.includes('<canvas'),'admin portal contains no face camera');
add(!employee.includes('<video')&&!employee.includes('<canvas'),'employee portal contains no face camera');
add(employee.includes('Complete My Shift')&&employeeJs.includes('checkoutMyAttendance'),'employee 8-hour shift checkout exists');
add(attendance.includes('<video')&&attendanceJs.includes('submitAttendanceLinkFace'),'face verification exists only on secure attendance link');
add(attendanceJs.includes('navigator.geolocation'),'attendance link captures mobile location');
add(admin.includes('id="employeeDialog" class="app-modal"')&&!admin.includes('<dialog id="employeeDialog"'),'employee form uses reliable custom modal instead of native dialog top-layer');
add(admin.includes('id="cancelEmployeeBtn"')&&admin.includes('type="button"')&&adminJs.includes("closeModal('employeeDialog')"),'employee Cancel/close controls are explicitly wired');
add(adminJs.includes("setInlineMessage('employeeFormMessage'")&&admin.includes('id="employeeFormMessage"'),'employee form errors render inside modal');
add(admin.includes('id="accessDialog" class="app-modal"')&&admin.includes('id="addAccessBtn"'),'access-management design uses dedicated add-account modal');
add(admin.includes('id="deleteAccessBtn"')&&adminJs.includes("call('deleteAccessUser'"),'admin/staff delete control is wired');
add(adminJs.includes('cfg.PRIMARY_ADMIN_EMAIL')&&config.includes("PRIMARY_ADMIN_EMAIL: 'incentifyprivatelimited@gmail.com'"),'primary administrator protected in frontend');
add(admin.includes('Mail Health')&&adminJs.includes("call('mailDiagnostics'")&&adminJs.includes("call('sendTestEmail'"),'mail diagnostics and end-to-end test email exist');
add(admin.includes('Application Run Descriptions')&&adminJs.includes("call('listSystemRuns'"),'backend run descriptions are visible in admin settings');
add(adminJs.includes("state.employees.push(saved)")&&!adminJs.slice(adminJs.indexOf('async function saveEmployee'),adminJs.indexOf('async function deleteEmployee')).includes('reloadAdmin'),'employee save updates local state without full bootstrap reload');
add(config.includes("VERSION: '18.0.0'")&&config.includes("BACKEND_VERSION: '18.0.0'"),'frontend targets V18 backend');
add(config.includes('AKfycbxXvyGi6PCfBMC0Tza9FK_s6P4ii6vRXJlRZR2o1iaJd5Hu00VCCefABW0Tca_kSlM8'),'production Apps Script deployment URL configured');
add(api.includes('__incentify_ems_v18_cb_')&&api.includes('_jsonpOnce'),'V18 JSONP callback contract configured');
const safeBlock=api.slice(api.indexOf('async _safeTransport'),api.indexOf('async _singleDeliveryTransport'));
add(safeBlock.indexOf('this._jsonpOnce')>=0&&safeBlock.indexOf('this._fetchOnce')>safeBlock.indexOf('this._jsonpOnce'),'safe transport prefers JSONP before fetch fallback');
add(api.includes("'mailDiagnostics','listMailLog','listSystemRuns'"),'new diagnostic reads use safe transport');
add(api.includes('_singleDeliveryTransport')&&api.includes('return this._jsonpOnce'),'unsafe mutations are single-delivery');
add(!adminJs.includes("api.call('health'")&&!adminJs.includes("api.call('validateSession'"),'admin startup avoids redundant health/session calls');
add(!employeeJs.includes("api.call('health'")&&!employeeJs.includes("api.call('validateSession'"),'employee startup avoids redundant health/session calls');
add(!attendanceJs.includes("api.call('health'")&&attendanceJs.includes('requestIdleCallback'),'attendance page removes redundant health call and prewarms face models');
add(attendance.includes('rel="preconnect" href="https://cdn.jsdelivr.net"'),'face-model CDN preconnect enabled');
add(index.includes('api-client.js?v=18.0.0')&&index.includes('auth.js?v=18.0.0'),'login assets cache-busted');
add(sw.includes('incentify-ems-v18-shell-1')&&sw.includes("url.searchParams.get('v')==='18.0.0'"),'V18 PWA cache isolation configured');
add(!api.includes('iframe')&&!api.includes('Bridge.html'),'no iframe bridge used');
add(workflow.includes('verify-v18.mjs')&&workflow.includes('Deploy INCENTIFY EMS V18'),'GitHub Pages verifies V18 before deployment');
add(deployTest.includes('$attempt -le 3')&&deployTest.includes('RECOVERED_TRANSIENTS'),'deployment test recovers transient Apps Script 404s');

add(admin.includes('id="confirmDialog"')&&adminJs.includes('confirmAction(')&&!adminJs.includes('confirm('),'destructive actions use custom confirmation modal');
add(admin.includes('mailLogBody')&&adminJs.includes("call('listMailLog'")&&adminJs.includes('renderMailLog'),'mail delivery log is visible in admin portal');
const failed=checks.filter(x=>!x.ok);for(const c of checks)console.log(`${c.ok?'PASS':'FAIL'}: ${c.n}`);if(failed.length){console.error(`\n${failed.length} frontend verification check(s) failed.`);process.exit(1);}console.log(`\nV18 frontend verification passed: ${checks.length} checks.`);
