import fs from 'node:fs';
const read=f=>fs.readFileSync(f,'utf8');
const admin=read('admin.html'),employee=read('employee.html'),attendance=read('attendance.html');
const adminJs=read('js/admin.js'),employeeJs=read('js/employee.js'),attendanceJs=read('js/attendance.js'),config=read('js/config.js'),api=read('js/api-client.js'),sw=read('sw.js');
const checks=[];const add=(ok,n)=>checks.push({ok:!!ok,n});
add(read('index.html').includes('Admin Login')&&read('index.html').includes('Employee Login'),'separate admin and employee login choices');
add(admin.includes('HOLIDAY CALENDAR')&&admin.includes('LATE ARRIVAL CONCESSION'),'admin holiday calendar and late-concession UI exist');
add(admin.includes('attendance_link')===false,'admin HTML does not expose backend internals');
add(!admin.includes('<video')&&!admin.includes('<canvas'),'admin portal contains no face camera');
add(!employee.includes('<video')&&!employee.includes('<canvas'),'employee portal contains no face camera');
add(employee.includes('Complete My Shift')&&employeeJs.includes('checkoutMyAttendance'),'employee shift checkout exists');
add(employeeJs.includes('getMyAttendance')&&!employeeJs.includes('saveMyBiometric')&&!employeeJs.includes('getMyRecognitionProfile'),'employee portal is attendance/checkout only');
add(attendance.includes('<video')&&attendanceJs.includes('submitAttendanceLinkFace'),'face verification exists only on secure attendance link');
add(attendanceJs.includes('navigator.geolocation'),'attendance link captures mobile location');
add(adminJs.includes('createLateConcession')&&adminJs.includes('saveHoliday'),'admin APIs cover concessions and holidays');
add(config.includes("VERSION: '14.0.0'"),'frontend is V14');
add(api.includes('__incentify_ems_v14_cb_'),'V14 JSONP transport configured');
add(sw.includes('./attendance.html')&&sw.includes('./js/attendance.js'),'PWA caches attendance capture page');
add(!admin.includes('Start recognition')&&!employee.includes('Capture my face'),'legacy portal face controls removed');
add(!api.includes('iframe')&&!api.includes('Bridge.html'),'no iframe bridge is used');
const failed=checks.filter(x=>!x.ok);for(const c of checks)console.log(`${c.ok?'PASS':'FAIL'}: ${c.n}`);if(failed.length){console.error(`\n${failed.length} frontend verification check(s) failed.`);process.exit(1);}console.log(`\nV14 frontend verification passed: ${checks.length} checks.`);
